approve_by_comment: true
approve_regex: ^Approved
reject_regex: ^Rejected
reset_on_push: false
reviewers:
  members:
  - duramato
  - fernandog
  - labrys
  - medariox
  - OmgImAlexis
  - pithoi
  name: default
  required: 1
